# Generated by Django 4.0.2 on 2022-02-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196, unique=True, verbose_name='title_category')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196, unique=True, verbose_name='title_city')),
            ],
            options={
                'db_table': 'city',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='telegram_id')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('first_name', models.CharField(max_length=64, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='last_name')),
                ('fio', models.CharField(blank=True, max_length=196, null=True, verbose_name='fio')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='birthday')),
                ('education', models.TextField(blank=True, null=True, verbose_name='education')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='experience')),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['first_name', 'last_name', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=196, verbose_name='title_organization')),
                ('details', models.TextField(blank=True, null=True, verbose_name='organization_details')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('phone', models.CharField(max_length=128, verbose_name='phone')),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datev', models.DateTimeField(verbose_name='datev')),
                ('position', models.CharField(max_length=196, verbose_name='position')),
                ('details', models.TextField(verbose_name='vacancy_details')),
                ('salary', models.CharField(max_length=196, verbose_name='salary')),
                ('date_close', models.DateTimeField(blank=True, null=True, verbose_name='datev')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_category', to='quest.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_city', to='quest.city')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_organization', to='quest.organization')),
            ],
            options={
                'db_table': 'vacancy',
                'ordering': ['datev'],
            },
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dater', models.DateTimeField(auto_now_add=True, verbose_name='dater')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respond_customer', to='quest.customer')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respond_vacancy', to='quest.vacancy')),
            ],
            options={
                'db_table': 'respond',
                'ordering': ['dater'],
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['title'], name='organizatio_title_be9d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['telegram_id'], name='customer_telegra_f5e35d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customer_phone_n_d31982_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['title'], name='city_title_fcc479_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='category_title_f3128f_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['city'], name='vacancy_city_id_02cdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['organization'], name='vacancy_organiz_f0f7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['category'], name='vacancy_categor_9c363e_idx'),
        ),
        migrations.AddIndex(
            model_name='respond',
            index=models.Index(fields=['vacancy'], name='respond_vacancy_e0c41f_idx'),
        ),
        migrations.AddIndex(
            model_name='respond',
            index=models.Index(fields=['customer'], name='respond_custome_678b33_idx'),
        ),
    ]
