# Generated by Django 4.0.1 on 2022-01-27 04:46

from django.db import migrations

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

def beginning(apps, schema_editor):
    
    # Суперпользователь id-1
    user = User.objects.create_superuser(username='root',
    email='vacancy2602@mail.ru',
    password='SsNn5678+-@')
    print("Суперпользователь создан")
    
       
    # Группа менеджеров
    managers = Group.objects.get_or_create(name = 'Managers')
    managers = Group.objects.get(name='Managers')
    print("Группа менеджеров создана")
    
    # Пользователь с ролью менеджера id8
    user = User.objects.create_user(username='manager', password='Ss0066+-')
    managers.user_set.add(user)
    print("Менеджер добавлен в группу менеджеров")

    ##### Города #####
    
    City = apps.get_model("quest", "City")
   
    city = City()
    city.title = 'Алматы'
    city.save()
    
    city = City()
    city.title = 'Нур-Султан'
    city.save()

    city = City()
    city.title = 'Шымкент'
    city.save()

    city = City()
    city.title = 'Актобе'
    city.save()

    city = City()
    city.title = 'Караганда'
    city.save()

    city = City()
    city.title = 'Атырау'
    city.save()

    city = City()
    city.title = 'Тараз'
    city.save()

    city = City()
    city.title = 'Павлодар'
    city.save()

    city = City()
    city.title = 'Семей'
    city.save()

    city = City()
    city.title = 'Усть-Каменогорск'
    city.save()

    print("Города добавлены")

    ##### Организация #####
    
    Organization = apps.get_model("quest", "Organization")
   
    organization = Organization()
    organization.title = 'АО "НК "Қазақстан темір жолы"'
    organization.details = '«Казахстан темир жолы» — крупнейший оператор магистральной железнодорожной сети Казахстана. Полное наименование — Акционерное общество «Национальная компания „Қазақстан темір жолы“».'
    organization.address = '​Дінмұхамед Қонаев, 6​1 этаж​55 филиалов Есиль район, Нур-Султан, Z05H9E6'
    organization.phone = '8-7172-60-67-66'
    organization.save()
    
    organization = Organization()
    organization.title = 'ТОО Корпорация Казахмыс'
    organization.details = 'Группа «Казахмыс» – вертикально- интегрированный холдинг, ключевые активы которого сосредоточены в горнодобывающей отрасли и цветной металлургии.'
    organization.address = '100012, Республика Казахстан, г. Караганда, ул. Абая, 12, каб. 102​'
    organization.phone = '+7 (721) 295-21-95, +7 (721) 295-26-12'
    organization.save()
    
    organization = Organization()
    organization.title = 'АО «Казхром»'
    organization.details = 'АО «ТНК «Казхром» представляет собой горно-металлургический кластер полного цикла, начиная от разведки недр, добычи полезных ископаемых и их обогащения и заканчивая металлургическим производством по выпуску продукции с высокой добавленной стоимостью.'
    organization.address = 'Республика Казахстан, 030008, Актобе, ул. М. Маметовой, 4А​'
    organization.phone = '+7 7132 973 112'
    organization.save()
    
    organization = Organization()
    organization.title = 'BI Group'
    organization.details = 'BI Group - крупный строительный холдинг, лидер на рынке недвижимости Казахстана. Холдинг работает с 1995 года и за это время заслужил репутацию профессионала и надежного партнера. BI Group сегодня – многопрофильный холдинг, структуру которой составляют дивизионы и дирекции в различных сферах строительства, девелопмента и инжиниринга.'
    organization.address = 'Нур-Султан, БЦ Viva Plaza ул. Сыганак, 62/3, ​'
    organization.phone = '360 Бесплатно с мобильного'
    organization.save()
    
    organization = Organization()
    organization.title = 'Magnum Cash&Carry'
    organization.details = '«Magnum Cash&Carry» — крупнейшая торгово-розничная сеть Казахстана, входит в десятку крупнейших частных компаний страны. Основной деятельностью является реализация товаров широкого потребления'
    organization.address = 'Адрес: г. Алматы, мкр. Астана, 1/10, ТЦ "Люмир", 4 этаж​'
    organization.phone = '+7 (727) 346 73 22'
    organization.save()
    
    organization = Organization()
    organization.title = 'KAZ Minerals'
    organization.details = 'KAZ Minerals — медедобывающая компания, ориентированная на развитие современных низкозатратных горнорудных производств в Казахстане.'
    organization.address = 'Проспект Достык 85А, Корпус 1, Алматы, 050021​'
    organization.phone = '+7 727 244 03 53'
    organization.save()
    
    organization = Organization()
    organization.title = 'Astana Motors'
    organization.details = 'Официальный дистрибьютор легковой и коммерческой техники Hyundai в Казахстане, официальный дистрибьютор Subaru в Казахстане, эксклюзивный импортер BMW, MINI, Motorrad в Казахстане, официальный дистрибьютор Haval и Chery в Казахстане, официальный дистрибьютор по производству и реализации пассажирского транспорта марки Golden Dragon в Казахстане, официальный дистрибьютор Foton в Казахстане'
    organization.address = 'г. Нур-Султан, правый берег, пр. Ш. Кудайбердыулы, 6/1'
    organization.phone = '+7 (7172) 27 04 04'
    organization.save()

    print("Организации добавлены")

    ##### Категория (вид деятельности) #####
    Category = apps.get_model("quest", "Category")

    category = Category()
    category.title = 'Продажи'
    category.save()

    category = Category()
    category.title = 'Начало карьеры'
    category.save()

    category = Category()
    category.title = 'Бухгалтерия'
    category.save()

    category = Category()
    category.title = 'IT, телеком'
    category.save()

    category = Category()
    category.title = 'Административный персонал'
    category.save()

    category = Category()
    category.title = 'Строительство'
    category.save()

    category = Category()
    category.title = 'Транспорт'
    category.save()

    category = Category()
    category.title = 'Производство'
    category.save()

    category = Category()
    category.title = 'Рабочий персонал'
    category.save()

    category = Category()
    category.title = 'Маркетинг'
    category.save()

    print("Категории добавлены")

    ##### Вакансии #####
    Vacancy = apps.get_model("quest", "Vacancy")

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 1
    vacancy.organization_id = 5
    vacancy.category_id = 1
    vacancy.position = 'Оператор зоны приемки'
    vacancy.details = 'Прием товара согласно сопроводительной документации, Ввод товарных позиций и создание приходных накладных в программе учета товара, Контроль работы грузчиков, Создание эффективно работающей команды'
    vacancy.salary = 'от 110 000 до 121 000 KZT на руки'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 1
    vacancy.organization_id = 5
    vacancy.category_id = 1
    vacancy.position = 'Продавец-кассир'
    vacancy.details = 'Открытие, ведение и закрытие кассовой смены; Проведение наличного и безналичного расчета; Учет и контроль денежной наличности в кассе;'
    vacancy.salary = 'з/п не указана'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 2
    vacancy.organization_id = 4
    vacancy.category_id = 10
    vacancy.position = 'Менеджер по работе с клиентами'
    vacancy.details = 'Прием входящих звонков от клиентов; Активная поддержка и сопровождение базы действующих клиентов; Полное сопровождение клиента от А до Я; Конвертация и обработка входящих запросов'
    vacancy.salary = 'от 250 000 до 500 000 KZT до вычета налогов'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 2
    vacancy.organization_id = 4
    vacancy.category_id = 10
    vacancy.position = 'Аналитик'
    vacancy.details = 'Анализ процессов смежных подразделений с последующим участием в разработке стратегии компании; Подготовка аналитических отчетов и предоставление руководству на постоянной основе и по запросу в наглядном виде (таблицы, графики, диаграммы и т.д.); Ведение документации по проектам Отдела автоматизации и внедрения; Участие в автоматизации процессов, связанных с деятельностью компании;'
    vacancy.salary = 'з/п не указана'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 1
    vacancy.organization_id = 7
    vacancy.category_id = 1
    vacancy.position = 'Оператор call-центра'
    vacancy.details = 'Принятие обращений; Предоставление обратной связи клиентам по их обращениям; Консультация клиентов, предоставление справочной информации; Проведение телефонных опросов'
    vacancy.salary = 'з/п не указана'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 4
    vacancy.organization_id = 1
    vacancy.category_id = 3
    vacancy.position = 'Помощник бухгалтера'
    vacancy.details = 'Ведение и контроль бухгалтерского и налогового учета компании в полном объеме; Организация и контроль бухгалтерского документооборота, первичной документации; Расчет и начисление заработной платы сотрудников.'
    vacancy.salary = 'до 240 000 KZT до вычета налогов'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 5
    vacancy.organization_id = 2
    vacancy.category_id = 5
    vacancy.position = 'Администратор'
    vacancy.details = 'Организует прием посетителей и распределение очередности клиентов в отделе; Приветствует клиентов, выясняет цель визита, постоянный клиент или новый, имя персонального менеджера и содействует оперативности обслуживания;'
    vacancy.salary = 'з/п не указана'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 6
    vacancy.organization_id = 3
    vacancy.category_id = 10
    vacancy.position = 'Data analyst'
    vacancy.details = 'Анализ клиентского пути; Анализ клиентской базы; Сквозная аналитика; Анализ основных показaтелей и генерация гипотез по точкам роста;'
    vacancy.salary = 'з/п не указана'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 7
    vacancy.organization_id = 4
    vacancy.category_id = 10
    vacancy.position = 'Руководитель проекта'
    vacancy.details = 'Формирование проектной команды и управление ею в рамках реализации проектов; Координация работ и организация мероприятий по реализации проекта, контроль качества их выполнения; Определение приоритетности и степени важности при распределении ресурсов'
    vacancy.salary = 'з/п не указана'   
    vacancy.save()

    vacancy = Vacancy()
    vacancy.datev = '2022-01-27 12:00:00'
    vacancy.city_id = 1
    vacancy.organization_id = 6
    vacancy.category_id = 4
    vacancy.position = 'Data Engineer (Junior)'
    vacancy.details = 'Разработка ETL- процессов; Разработка структуры данных в колончатой СУБД - курирование процесса разработки , контроль качества, разбор проблем; Разработка процессов извлечения данных из систем источников- курирование процесса разработки, контроль качества, разбор проблем;'
    vacancy.salary = 'от 200 000 до 300 000 KZT до вычета налогов'   
    vacancy.save()
    
    print("Вакансии добавлены")

class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(beginning),        
    ]


